# 2026-04-09 06:29:29
# DNS：quic://dns.alidns.com:853
# 数量：30

DOMAIN-SUFFIX,taobao.com
DOMAIN-SUFFIX,tmall.com
DOMAIN-SUFFIX,alipay.com
DOMAIN-SUFFIX,alicdn.com
DOMAIN-SUFFIX,aliyun.com
DOMAIN-SUFFIX,aliyundrive.com
DOMAIN-SUFFIX,sina.com.cn
DOMAIN-SUFFIX,cn
DOMAIN-SUFFIX,taobao.org
DOMAIN-SUFFIX,aliapp.org
DOMAIN-SUFFIX,aliyundrive.net
DOMAIN-SUFFIX,alibabausercontent.com
DOMAIN-SUFFIX,alibabachengdun.com
DOMAIN-SUFFIX,alipayobjects.com
DOMAIN-SUFFIX,aliyundrive.com
DOMAIN-SUFFIX,alibaba-inc.com
DOMAIN-SUFFIX,alibabadns.com
DOMAIN-SUFFIX,taobaocdn.com
DOMAIN-SUFFIX,alipaydev.com
DOMAIN-SUFFIX,myalicdn.com
DOMAIN-SUFFIX,aliyuncs.com
DOMAIN-SUFFIX,ialicdn.com
DOMAIN-SUFFIX,alibaba.com
DOMAIN-SUFFIX,taobao.com
DOMAIN-SUFFIX,aliyun.com
DOMAIN-SUFFIX,alipay.com
DOMAIN-SUFFIX,alicdn.com
DOMAIN-SUFFIX,tmall.com
DOMAIN-SUFFIX,1688.com
DOMAIN-SUFFIX,alipay.cn